[workspace]
resolver = "3"
members = [
    "crates/*",
]
exclude = [
    "editors/zed-styx",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bearcove/styx"

[workspace.dependencies]
# Error reporting
ariadne = "0.4"

# Facet crates
facet = "0.42"
facet-args = "0.42"
facet-core = "0.42"
facet-format = "0.42"
facet-reflect = "0.42"
facet-testhelpers = { git = "https://github.com/facet-rs/facet" }

# Tracing
tracing = "0.1"

# Testing
insta = "1"

# Internal crates
styx-parse = { path = "crates/styx-parse" }
styx-format = { path = "crates/styx-format" }
styx-tree = { path = "crates/styx-tree" }
styx-schema = { path = "crates/styx-schema" }
styx-cst = { path = "crates/styx-cst" }
styx-lsp = { path = "crates/styx-lsp" }
facet-styx = { path = "crates/facet-styx" }

[patch.crates-io]
facet = { path = "../facet/facet" }
facet-args = { path = "../facet/facet-args" }
facet-core = { path = "../facet/facet-core" }
facet-format = { path = "../facet/facet-format" }
facet-reflect = { path = "../facet/facet-reflect" }
