specs:
  - name: parser
    prefix: parser
    include:
      - docs/content/spec/parser.md
    impls:
      - name: rust
        include:
          - "**/*.rs"

  - name: schema
    prefix: schema
    include:
      - docs/content/spec/schema.md
    impls:
      - name: rust
        include:
          - "**/*.rs"

  - name: diagnostics
    prefix: diag
    include:
      - docs/content/spec/diagnostics.md
    impls:
      - name: rust
        include:
          - "**/*.rs"
