id = "styx"
name = "Styx"
description = "Styx configuration language support with syntax highlighting"
version = "0.1.0"
schema_version = 1
authors = ["Amos Wenger <amos@bearcove.eu>"]
repository = "https://github.com/bearcove/styx"

[grammars.styx]
repository = "https://github.com/bearcove/styx"
path = "crates/tree-sitter-styx"
rev = "97ecbd622911fd6632782d72f924fec83eeacd8c"
