[package]
name = "styx-cli"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "styx"
path = "src/main.rs"

[dependencies]
styx-tree.workspace = true
styx-parse.workspace = true
facet.workspace = true
facet-args.workspace = true
serde_json = "1"

[dev-dependencies]
